### ISSUE TITLE
Service für Backend Kommunikation

### ISSUE THREAD

**Issue by JannickFaber** [JannickFaber/covidiary#10]
Service für Backend Kommunikation anlegen. Mit Johannes bzgl. Schnittstellen absprechen.

**Comment by jo2** [comment]
Schnittstellen von meiner Seite sind in der Swagger API dokumentiert. Backend starten -> localhost:8080/swagger-ui.html

Können da aber auch gerne noch drüber reden wenn ihr verbesserungsvorschläge habt,
